package main

import (
	"fmt"
	"os"

	"github.com/equinox-io/equinox"
)

// assigned when creating a new application in the dashboard
const appID = "app_4xCaMumNoeF"

// application version
var version string

// public portion of signing key generated by `equinox genkey`
var publicKey = []byte(`
-----BEGIN ECDSA PUBLIC KEY-----
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAESYHcYsiu18n8vFslTBeM0PAfzq2gifV7
OTwj/8Jda4omURmtygToJkHyZivkuLP48S1cFnTBlk8NHRlfD+rDdj5g+ZTgA4dT
5mM1cYPmRGK2lCxazL9JL4QBQQ+jQsqr
-----END ECDSA PUBLIC KEY-----
`)

func equinoxUpdate() error {
	var opts equinox.Options
	if err := opts.SetPublicKeyPEM(publicKey); err != nil {
		return err
	}

	// check for the update
	resp, err := equinox.Check(appID, opts)
	switch {
	case err == equinox.NotAvailableErr:
		fmt.Println("No update available, already at the latest version!")
		return nil
	case err != nil:
		fmt.Println("Update failed:", err)
		return err
	}

	// fetch the update and apply it
	err = resp.Apply()
	if err != nil {
		return err
	}

	fmt.Printf("Updated to new version: %s!\n", resp.ReleaseVersion)
	return nil
}

func main() {
	if len(os.Args) == 2 && os.Args[1] == "update" {
		equinoxUpdate()
	}
	fmt.Printf("Travis CI example current version: %s\n", version)
}
